faq = [
    "Who made Penpot and why?",
    "Kaleidos Open Source created Penpot to provide a free, open-source UX/UI tool for cross-domain teams, bridging the gap between design and code, and making it accessible to everyone.",
    "Why specifically Open Source?",
    "Open source promotes a fairer society with more evenly distributed opportunities, fosters engaging communities, and allows for digital sovereignty; Penpot chose the Mozilla Public License 2.0 for consistent rules across web and native software.",
    "Why is SVG its native format?",
    "SVG is used as Penpot's native format because it enhances technology sovereignty, simplifies design-code cooperation, supports cross-domain team focus, and eliminates platform dependencies, promoting universal access.",
    "How is Penpot different from proprietary products?",
    "Penpot's distinct features include open source (offering technology sovereignty), SVG format (easier design-code cooperation), cross-domain team focus (embraced by both designers and developers), and no platform dependencies (browser-based, with a native app in development).",
    "Why use Clojure and Clojurescript for Penpot?",
    "Clojure and Clojurescript, as functional programming languages, excel at high-performance web tasks and manipulating mathematical objects, making them ideal for building a robust tool like Penpot in a short time.",
    "What are the plans to charge for Penpot at some point?",
    "Penpot plans to charge for enterprise features needed by medium to large organizations for legal or security compliance and senior management tools while keeping core features open source and free for power users.",
    "Is there a Desktop app option for Penpot?",
    "Yes, there is a community-contributed Penpot Desktop app by Korbs under active development, offering a desktop-like experience for individual use, but it is not officially supported yet.",
    "Where can I find the Penpot code?",
    "You can download the code or clone the repository at Github: https://github.com/penpot",
    "How can I enjoy the best Penpot browser experience?",
    "Cross-browser support is a key aspect of Penpot so we give much thought and care to it. Our current preference solely in terms of experience is: Chrome (or Chromium/Blink based browsers/Edge), Firefox, WebKit (Safari / Epiphany)",
    "How can I collaborate with others in Penpot?",
    "Create a team",
    "How can I share my designs with external stakeholders?",
    "Go to VIEW mode: launch it using the PLAY button at the top right of the file, and you’ll find a SHARE URL button to create the link at the top right. Copy the link and send that link for other people to access the design.",
    "How can I stay up-to-date with the latest Penpot news and what’s to come?",
    "We will be sharing our progress and news through different channels: Penpot Social Networks, Penpot Youtube channel, Newsletter, Penpot Github Project",
    "How can I use Penpot together with Inkscape?",
    "Use Inkscape to create vector illustrations, icon sets, and graphic assets, then import them into Penpot to design more comprehensive and visually appealing interfaces, complementing your workflow with other tools like Quant-UX for user interaction insights.",
    "How can I learn how to use Penpot?",
    "Right now, our suggested approach would be to take a look at our Youtube channel 5 and enjoy the quick tutorials on many aspects of Penpot.",
    "How can I contribute to Penpot?",
    "Contribute to Penpot in areas like code (report bugs, work on enhancements, or help with the exporter), UX/UI (create libraries, templates, or provide feedback), and languages (assist with translations by requesting access to Weblate). Reach out for guidance or information if needed.",
    "Has Penpot kept a familiar pattern from reference tools despite potential improvements?",
    "No, Penpot doesn't keep patterns just for familiarity. While familiar patterns are used to ease the learning curve, design decisions are also based on user testing, and improvements are made when a better solution is found, like with masks and toolbars."
]

shortcuts = [
    "How can I align items to the bottom in Penpot?",
    "Use the \"Align bottom\" shortcut by pressing Alt+S on Linux and Windows, or ⌥S on macOS.",
    "How can I align items horizontally to the center in Penpot?",
    "Use the \"Align center horizontally\" shortcut by pressing Alt+H on Linux and Windows, or ⌥H on macOS.",
    "How can I align items vertically to the center in Penpot?",
    "Use the \"Align center vertically\" shortcut by pressing Alt+V on Linux and Windows, or ⌥V on macOS.",
    "How can I align items to the left in Penpot?",
    "Use the \"Align left\" shortcut by pressing Alt+A on Linux and Windows, or ⌥A on macOS.",
    "How can I align items to the right in Penpot?",
    "Use the \"Align right\" shortcut by pressing Alt+D on Linux and Windows, or ⌥D on macOS.",
    "How can I align items to the top in Penpot?",
    "Use the \"Align top\" shortcut by pressing Alt+W on Linux and Windows, or ⌥W on macOS.",
    "How can I distribute items horizontally in Penpot?",
    "Use the \"Distribute horizontally\" shortcut by pressing Ctrl+Shift+Alt+H on Linux and Windows, or ⌘⇧⌥H on macOS.",
    "How can I distribute items vertically in Penpot?",
    "Use the \"Distribute vertically\" shortcut by pressing Ctrl+Shift+Alt+V on Linux and Windows, or ⌘⇧⌥V on macOS.",
    "How can I cancel an action in Penpot?",
    "Use the \"Cancel\" shortcut by pressing Esc on both Linux and Windows, and macOS.",
    "How can I clear the undo history in Penpot?",
    "Use the \"Clear undo\" shortcut by pressing Ctrl+Q on Linux and Windows, or Alt+Q on macOS.",
    "How can I copy selected items in Penpot?",
    "Use the \"Copy\" shortcut by pressing Ctrl+C on Linux and Windows, or ⌘C on macOS.",
    "How can I cut selected items in Penpot?",
    "Use the \"Cut\" shortcut by pressing Ctrl+X on Linux and Windows, or ⌘X on macOS.",
    "How can I delete selected items in Penpot?",
    "Use the \"Delete\" shortcut by pressing Supr or Delete on Linux and Windows, or ⌫ on macOS.",
    "How can I duplicate selected items in Penpot?",
    "Use the \"Duplicate\" shortcut by pressing Ctrl+D on Linux and Windows, or ⌘D on macOS.",
    "How can I paste copied items in Penpot?",
    "Use the \"Paste\" shortcut by pressing Ctrl+V on Linux and Windows, or ⌘V on macOS.",
    "How can I redo an action in Penpot?",
    "Use the \"Redo\" shortcut by pressing Ctrl+Shift+Z on Linux and Windows, or ⌘⇧Z on macOS."
]
